kind: pipeline
type: docker
name: build golang

steps:
  - name: code-analysis
    image: sonarsource/sonar-scanner-cli
    commands:
      - export SONAR_HOST_URL=http://192.168.21.9:9000
      - export SONAR_SCANNER_OPTS=-Dsonar.projectKey=drone_test_1
      - export SONAR_TOKEN=sqp_090406d4ffdf6c81c1dde59e0a371ef6c34cec6e
      - sonar-scanner
