kind: pipeline
type: docker
name: build golang

steps:
  - name: build
    image: golang:latest
    commands:
      - cd ./greetings
      - go build
      - go test

  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host: 
        from_secret: SONAR_HOST
      sonar_token: 
        from_secret: SONAR_TOKEN
