kind: pipeline
type: docker
name: build golang

steps:
  - name: code-analysis
    image: sonarsource/sonar-scanner-cli
    environment:
      SONAR_HOST_URL:
        from_secret: SONAR_HOST
      SONAR_SCANNER_OPTS:
        from_secret: SONAR_PROJECT_KEY
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
    commands:
      - sonar-scanner
